setup: Added dependency checking

diff --git a/.setup/jsetup b/.setup/jsetup
--- a/.setup/jsetup
+++ b/.setup/jsetup
@@ -2,6 +2,23 @@
 
 source common
 
+check_dependency() {
+    local q # Question
+
+    $1 -h 2>&1 1>/dev/null
+    if [ $? -eq 0 ]; then
+        return 0
+    fi
+    echo "Package $1 required!"
+    echo -n "Install? [Y/n]: "
+    read q
+    if [ "$q" == "y" ] || [ "$q" == "Y" ] || ["$q" == "" ]; then
+        sudo apt-get install "$2"
+        return 0
+    fi
+    exit 1
+}
+
 
 get_distro() {
     file="packages/distros"
@@ -43,6 +60,8 @@ get_packages() {
 
 main() {
     sudo -v
+
+    check_dependency dialog dialog
 
     # Get Distro
     distro=$(get_distro)
